language: python
python:
  - "3.3"
  - "2.7"
# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install nose"
# command to run tests
script:
  nosetests --with-coverage
after_success:
  coveralls
