language: python
python:
  - "3.3"
# command to install dependencies
before_install:
 - "pip install six>=1.3"
 - "pip install cython>=0.21"
 - "pip install scipy>=0.14"

install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "pip install nose"
# command to run tests
script:
  nosetests --with-coverage
after_success:
  coveralls
