language: python
python:
  - "3.3"
install:
  # Install conda
  - sudo pip install conda -H
  # install deps
  - sudo conda init -H
  - sudo conda update conda --yes -H
  - deps='pip numpy scipy nose scikit-image'
  - conda create -p $HOME/py --yes $deps "python=$TRAVIS_PYTHON_VERSION"
  - export PATH=$HOME/py/bin:$PATH
  # install your own package into the environment
  - python setup.py install
script:
- "nosetests -w test/ -v"
